### ISSUE TITLE
errno cli name conflicts with the linux utility

### ISSUE THREAD

**Issue by abdulhannanali** [rvagg/node-errno#32]
I suggest that errno cli application also be exposed on another name, in case [errno](http://man7.org/linux/man-pages/man3/errno.3.html) tool is already installed since this tool is readily available on many of the linux distributions and people using debian can install it using `apt-get`. 

Without uninstalling that linux tool it's impossible for bash to reach this one without directly accessing the path of the node executable file. 

Two identical files would be suffice to keep the tool entirely backwards compatible.

**Comment by Alessandro-Barbieri** [comment]
I'm packaging this for gentoo and I hit this. Any progress?

**Comment by ralphtheninja** [comment]
I wasn't aware of the problem until now. Maybe name it `node-errno` like the module? Or `errnode`? :)

**Comment by Alessandro-Barbieri** [comment]
I don't have preferences for the filename

**Comment by ralphtheninja** [comment]
@rvagg Any thoughts about this? Naming things, yay!

**Comment by rvagg** [comment]
`errno(3)` is a header file, not a tool. This library has just as much a legitimate claim to the non-standard `errno` cli tool that _doesn't come installed by default on most systems_ (any systems?). This package is also "readily available on linux distributions using `npm install`". I don't really care that much about any of this but this line of argument is pretty silly. "I can get something via `apt` therefore this other thing with the same name needs to change its name".

**Comment by Alessandro-Barbieri** [comment]
It conflicts with [errno1](https://manpages.debian.org/stretch/moreutils/errno.1.en.html)

Also please read this https://docs.fedoraproject.org/en-US/packaging-guidelines/Conflicts/

**Comment by rvagg** [comment]
[moreutils](https://joeyh.name/code/moreutils/) is simply not part of the Unix or Linux canon, it just happens to be available via various package managers, as this package is available via the npm package manager and even directly via some Linux package managers. You're going to have to establish a criteria by which moreutils has more authority to this name in that particular namespace. Again, I don't care, and I don't know if anyone even uses the `"bin"` in here, I just find this line of argumentation silly.
